version: '3.2'

volumes:
  pg_data:
    driver: local

services:
  db:
    image: postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    ports:
      - '5435:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3006:3000'
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      WEBPACKER_DEV_SERVER_HOST: webpack
    stdin_open: true
    tty: true
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
  

